---
#
# Configure users.
#

- name: Create "{{ deploy.username }}" group
  group:
      name: "{{ deploy.username }}"
      system: no
      state: present


- name: Create "{{ deploy.username }}"  user
  user:
      name: "{{ deploy.username }}"
      password: "{{ deploy.password }}"
      group: "{{ deploy.username }}"
      home: "{{ deploy.home }}"
      createhome: yes
      skeleton: yes
      system: no
      shell: /bin/bash
      state: present


- name: Create SSH directory
  file:
      path: "{{ deploy.home }}/.ssh"
      owner: "{{ deploy.username }}"
      group: "{{ deploy.username }}"
      mode: "0500"
      state: directory


- name: Configure SSH private key
  copy:
      src: authorized_keys
      dest: "{{ deploy.home }}/.ssh/authorized_keys"
      owner: "{{ deploy.username }}"
      group: "{{ deploy.username }}"
      mode: "0400"
  register: result


- name: Configure systemd permissions for {{ deploy.unsername }}
  lineinfile:
    dest: /etc/sudoers
    line: "{{ item }}"
    state: present
  with_items:
    - "{{ deploy.username }} ALL=NOPASSWD: /bin/systemctl enable unitime-celery.service"
    - "{{ deploy.username }} ALL=NOPASSWD: /bin/systemctl enable unitime.service"
    - "{{ deploy.username }} ALL=NOPASSWD: /bin/systemctl status unitime-celery.service"
    - "{{ deploy.username }} ALL=NOPASSWD: /bin/systemctl status unitime.service"
    - "{{ deploy.username }} ALL=NOPASSWD: /bin/systemctl restart unitime-celery.service"
    - "{{ deploy.username }} ALL=NOPASSWD: /bin/systemctl restart unitime.service"


- name: Create bashrc
  lineinfile:
    dest: "{{ deploy.home }}/.profile"
    line: "{{ item }}"
    state: present
    create: yes
    owner: "{{ deploy.username }}"
    group: "{{ deploy.username }}"
  with_items:
    - "export PYTHON_ENV={{ target }}"
