---
#
# Kodkollektivet.se project related tasks
#

# Systemd stuff
- name: Copy kodkollektivetse.service to systemd folder
  template:
    src: kodkollektivetse.service.j2
    dest: /etc/systemd/system/kodkollektivetse.service
  notify: Reload systemd daemon


- name: Copy kodkollektivetse-celery.service to systemd folder
  template:
    src: kodkollektivetse-celery.service.j2
    dest: /etc/systemd/system/kodkollektivetse-celery.service
  notify: Reload systemd daemon


# Project directories
- name: Create base folder and set permissions
  file:
    path: "{{ projectpaths.base }}"
    state: directory
    owner: "{{ deploy.username }}"
    group: "{{ deploy.username }}"


- name: Create repo folder and set permissions
  file:
    path: "{{ projectpaths.repo }}"
    state: directory
    owner: "{{ deploy.username }}"
    group: "{{ deploy.username }}"


- name: Create current folder and set permissions
  file:
    path: "{{ projectpaths.current }}"
    state: directory
    owner: "{{ deploy.username }}"
    group: "{{ deploy.username }}"


- name: Create backup folder and set permissions
  file:
    path: "{{ projectpaths.backup }}"
    state: directory
    owner: "{{ deploy.username }}"
    group: "{{ deploy.username }}"


- name: Create secrets folder and set permissions
  file:
    path: "{{ projectpaths.secrets }}"
    state: directory
    owner: "{{ deploy.username }}"
    group: "{{ deploy.username }}"


- name: Create tmp folder and set permissions
  file:
    path: "{{ projectpaths.tmp }}"
    state: directory
    owner: "{{ deploy.username }}"
    group: "{{ deploy.username }}"


# Git clone
- git:
    repo: '{{ gitrepo }}'
    dest: "{{ projectpaths.repo }}"
    clone: yes
    update: no
