# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userprofile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('Student', 'Student'), ('Board', 'Board'), ('Support', 'Support')], default='Student', max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('valid_to', models.DateField()),
                ('board_position', models.CharField(choices=[('None', 'None'), ('President', 'President'), ('Vice President', 'Vice President'), ('Treasurer', 'Treasurer'), ('Internal Relations', 'Internal Relations'), ('External Relations', 'External Relations')], default='None', max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to=userprofile.models.get_upload_file_name)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
