version: '3'
services:
  koddjango:
    build: .
    container_name: koddjango
    stdin_open: true
    entrypoint: ./entrypoint.sh
    command: python3 kodkollektivet/manage.py runserver 0.0.0.0:8000
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
