version: '3'
services:
  koddjango:
    build: .
    container_name: koddjango
    stdin_open: true
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py compilemessages -l sv -l en && python3 manage.py runserver 0.0.0.0:8000"
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
