
* Vad är Kodkollektivet
** SV
Kodkollektivet består av en grupp studenter med ett brinnande
intresse, främst inom programmering, nätverk och andra IT-relaterade
ämnen. Vi startade under sommaren 2015 med ett hav av idéer som vi
sedan dess har provat på, finslipat men framför allt lärt oss en hel
del av gällande både samarbete, planering och fokus.

Med detta i bagaget startar Kodkollektivet nu som studentförening och
skiftar fokus en aning från projektarbeten och kodträffar till en mer social
platform inriktad på studenter (med ingen till full kompetens inom
sitt område) likaväl som företag med intresse av att komma i tidig
kontakt med framtida arbetstagare.

Detta gör vi med hjälp av en
mötesplats där studenter får komma i kontakt med båda varandra och
näringsliv genom diverse aktiviteter såsom tema-kvällar, hackathons,
workshops, studiebesök och kortare gästföreläsningar från företag i
regionen.

** ENG
Kodkollektivet consists of a group of students with a great interest
in programming, computer networking and tons of other IT and business
related topics. We started in the summer of 2015 with tons of ideas
that we since then have been trying out, refined and most importantly
learned a great deal from in terms of cooperation, planning and
focus.

With all of this Kodkollektivet is now taking the shape of a student
organization at Linnaeus University. Focus has shifted slightly from
project development and code meetups to more of a social platform
where students and local businesses can find, meet and get to know
each other through events and activities such as theme-nights,
hackathons, workshops, study visits, guest lectures and more.

As a result of this students at Linnaeus University are provided with
a place to find other students with a shared or similar interest,
while at the same time giving companies in the Vaxjo area the
opportunity to get a head start with potential employees.

* Student, har du vad som krävs
** SV
Absolut! För att ta del av Kodkollektivet krävs inga som helst
tidigare erfarenheter eller särskilda talanger. Vi välkomnar alla som
vill lära sig mer, förbättra sitt CV, eller bara träffa nya vänner med
liknande intressen!

Kodkollektivet ställer inga krav på dig som student, utan ger dig bara
möjligheten. Du bestämmer själv hur mycket du vill delta och hur
mycket tid du vill lägga ner på de aktiviteter och träffar vi
erbjuder.

** ENG
Absolutely! No previous experience or particular skills are required
to take part of Kodkollektivet. We welcome anyone who wants to learn,
share, improve their resume or just want to make more friends with
similar interests!

Kodkollektivet puts no requirements on you as a student, but is rather
a provider of opportunities. You are free to decide for yourself how
much you would like to participate and how much time you want to put
into the activities and events we host.

* Företagare, kom och träffa framtiden
** SV
Dagens studenter är de som kommer att driva nya ideer och tankar i
morgondagens företag. Genom Kodkollektivet finns möjligheten att på ett
prestigelöst och socialt sätt träffa dem. Kodkollektivet ser gärna att
ni kommer med ideer på events, föreläsningar eller studiebesök! Vill
ni vara med och sponsra Kodkollektivet och få din logo på hemsidan?

** ENG
The university students of today are the very people who will be
urging new thoughts and ideas in tomorrows businesses. Through
Kodkollektivet is the possibility to meet these students in a social,
comfortable environment without prestige. Kodkollektivet is always
open to any type of suggestions from you as a company, in regards of
ideas for events and activities.
