---
#
# Nginx handlers.
#

- name: Reload Nginx
  become: true
  service:
    name: nginx
    state: restarted


- name: Restart Nginx
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
