# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kodkollektivet', '0004_boardmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='position',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
