# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodkollektivet', '0006_auto_20170902_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='photo',
            field=models.ImageField(height_field=250, upload_to='board-images/', width_field=250),
        ),
    ]
