# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254)),
                ('slug', models.CharField(blank=True, max_length=254)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=254)),
                ('linkedin', models.CharField(blank=True, max_length=254)),
                ('about', models.TextField(blank=True, help_text='Markdown syntax')),
                ('gh_login', models.CharField(max_length=254)),
                ('gh_url', models.CharField(max_length=254)),
                ('gh_id', models.IntegerField()),
                ('gh_html', models.CharField(blank=True, max_length=254)),
                ('gh_avatar', models.CharField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('publish', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Event posts',
                'ordering': ['-created_date'],
                'verbose_name': 'Event post',
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('slug', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('slug', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProCon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Contributor')),
            ],
            options={
                'verbose_name': 'Project-Contributor relation',
            },
        ),
        migrations.CreateModel(
            name='ProFra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Framework')),
            ],
            options={
                'verbose_name': 'Project-Framework relation',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('gh_name', models.CharField(blank=True, max_length=254)),
                ('gh_id', models.IntegerField(blank=True, null=True)),
                ('gh_url', models.CharField(blank=True, max_length=254)),
                ('gh_readme', models.TextField(blank=True, help_text='Project readme. Markdown syntax!')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ProLan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Project')),
            ],
            options={
                'verbose_name': 'Project-Language relation',
            },
        ),
        migrations.CreateModel(
            name='ProRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Contributor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Project')),
            ],
            options={
                'verbose_name': 'Project-Role-Contributor relation',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=254)),
                ('slug', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='prorol',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Role'),
        ),
        migrations.AddField(
            model_name='profra',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Project'),
        ),
        migrations.AddField(
            model_name='procon',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodkollektivet.Project'),
        ),
    ]
