# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodkollektivet', '0003_project_in_focus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(max_length=50)),
                ('photo', models.ImageField(height_field=250, upload_to='', width_field=250)),
            ],
        ),
    ]
