# Generated by Django 2.0.4 on 2018-04-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodkollektivet', '0008_auto_20170902_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procon',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='procon',
            name='project',
        ),
        migrations.RemoveField(
            model_name='profra',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='profra',
            name='project',
        ),
        migrations.RemoveField(
            model_name='prolan',
            name='language',
        ),
        migrations.RemoveField(
            model_name='prolan',
            name='project',
        ),
        migrations.RemoveField(
            model_name='prorol',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='prorol',
            name='project',
        ),
        migrations.RemoveField(
            model_name='prorol',
            name='role',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Framework',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='ProCon',
        ),
        migrations.DeleteModel(
            name='ProFra',
        ),
        migrations.DeleteModel(
            name='ProLan',
        ),
        migrations.DeleteModel(
            name='ProRol',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
