# Generated by Django 2.0.4 on 2018-04-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodkollektivet', '0009_auto_20180405_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='gh_id',
            new_name='github_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='gh_name',
            new_name='github_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='gh_readme',
            new_name='github_readme',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='gh_url',
            new_name='github_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='in_focus',
        ),
    ]
