# Generated by Django 2.0.4 on 2018-04-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodkollektivet', '0010_auto_20180405_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_readme',
        ),
    ]
