# Generated by Django 2.0.4 on 2018-04-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodkollektivet', '0011_auto_20180405_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
